//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYRTEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Department { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthdate { get; set; }
        public System.DateTime DateOfEmployment { get; set; }
        public int Salary { get; set; }
        public int Age { get; set; }
    }
}
